name: $(Date:yyyyMMdd)

trigger:
  - main

pr: none

variables:
  azureContainerRegistry.repository: 'servicecanadalabs'
  azureContainerRegistry.name: 'DTS Shared Container Repo 10/11/2023'
  azureContainerRegistry.domain: 'dtsshared.azurecr.io'
  tag: 'ADO-$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build and Push to ACR
    jobs:
      - job: Build
        displayName: Build and Push Container
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: '$(azureContainerRegistry.name)'
              repository: '$(azureContainerRegistry.repository)'
              command: 'login'
          - script: "docker pull $(azureContainerRegistry.domain)/$(azureContainerRegistry.repository):latest"
            displayName: Pull latest for layer caching
            continueOnError: true
          - task: Docker@2
            inputs:
              containerRegistry: '$(azureContainerRegistry.name)'
              repository: '$(azureContainerRegistry.repository)'
              command: 'build'
              Dockerfile: './Dockerfile'
              tags: |
                $(tag)
                latest
                release-candidate
              arguments: |
                --pull 
                --build-arg NEXT_PUBLIC_BUILD_ID=$(ADO_BUILD) 
                --build-arg NEXT_PUBLIC_BUILD_DATE=$(BUILD_DATE) 
                --build-arg ADOBE_ANALYTICS_URL=$(ADOBE_ANALYTICS_URL) 
                --build-arg ISR_ENABLED=$(ISR_ENABLED) 
                --build-arg THANK_YOU_EMAIL=$(THANK_YOU_EMAIL) 
                --build-arg AEM_GRAPHQL_ENDPOINT=$(AEM_GRAPHQL_ENDPOINT) 
                --build-arg AEM_BASE_URL=$(AEM_BASE_URL)
                --build-arg AEM_CONTENT_FOLDER=$(AEM_CONTENT_FOLDER)
                --build-arg REVALIDATION_TOKEN=$(REVALIDATION_TOKEN) 
                --build-arg GIT_SHA=$(Build.SourceVersion)
                --build-arg ENVIRONMENT=$(ENVIRONMENT)
                --build-arg NOTIFY_API_KEY=$(NOTIFY_API_KEY)
                --build-arg NOTIFY_FEEDBACK_TEMPLATE_ID=$(NOTIFY_FEEDBACK_TEMPLATE_ID)
                --build-arg SUBMIT_FEEDBACK_EMAIL=$(SUBMIT_FEEDBACK_EMAIL)
                
          - task: Docker@2
            inputs:
              containerRegistry: '$(azureContainerRegistry.name)'
              repository: '$(azureContainerRegistry.repository)'
              command: 'push'
              tags: |
                $(tag)
                latest
                release-candidate