trigger:
- none
pr: 
- main

pool:
  vmImage: ubuntu-latest

variables:
  azure.servicePrincipal: 'SCLabsDev'
  webapp.name: 'alphasite-appservice-dev'
  webapp.resourceGroup: 'AlphasiteAppserviceRG'
  webapp.slotName: null
  azureContainerRegistry.name: 'alphasiteCRdev-7/10/2023'
  azureContainerRegistry.repository: 'alphasite'
  azureContainerRegistry.domain: 'alphasitecrdev.azurecr.io'
  azureContainerRegistry.tag: 'preview-$(Build.SourceVersion)'
  System.Debug: false

steps:
- task: Docker@2
  inputs:
    containerRegistry: '$(azureContainerRegistry.name)'
    repository: '$(azureContainerRegistry.repository)'
    command: 'login'
- script: "docker pull alphasitecrdev.azurecr.io/$(azureContainerRegistry.repository):latest"
  displayName: Pull latest for layer caching
  continueOnError: true

- task: Docker@2
  displayName: "Build image"
  inputs:
    containerRegistry: '$(azureContainerRegistry.name)'
    repository: '$(azureContainerRegistry.repository)'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(azureContainerRegistry.tag)
      latest
    arguments: |
      --cache-from alphasitecrdev.azurecr.io/$(azureContainerRegistry.repository):latest
      --build-arg NEXT_PUBLIC_BUILD_ID=$(ADO_BUILD) 
      --build-arg NEXT_PUBLIC_BUILD_DATE=$(BUILD_DATE)
      --build-arg MONGO_DB=$(MONGO_DB) 
      --build-arg ADOBE_ANALYTICS_URL=$(ADOBE_ANALYTICS_URL) 
      --build-arg NEXT_PUBLIC_NOTIFY_REPORT_A_PROBLEM_EMAIL=$(NEXT_PUBLIC_NOTIFY_REPORT_A_PROBLEM_EMAIL) 
      --build-arg THANK_YOU_EMAIL=$(THANK_YOU_EMAIL) 
      --build-arg AEM_GRAPHQL_ENDPOINT=$(AEM_GRAPHQL_ENDPOINT) 
      --build-arg REVALIDATION_TOKEN=$(REVALIDATION_TOKEN) 
      --build-arg GIT_SHA=$(GIT_SHA)

- task: Docker@2
  displayName: "Push image"
  inputs:
    containerRegistry: '$(azureContainerRegistry.name)'
    repository: '$(azureContainerRegistry.repository)'
    command: 'push'
    tags: |
      $(azureContainerRegistry.tag)
      latest

- task: PowerShell@2
  displayName: 'Decide which AppService slot to put this preview in'
  inputs:
    targetType: 'inline'
    script: |
      [int] $slotNumber = $System.PullRequest.PullRequestId%4
      Write-Host "$slotNumber"
      Write-Host "##vso[task.setvariable variable=webapp.slotName]$slotNumber"

- task: AzureCLI@2
  displayName: 'Create new slot in App Service'
  inputs:
    azureSubscription: $(azure.servicePrincipal)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az webapp deployment slot create --name $(webapp.name) --resource-group $(webapp.resourceGroup) --slot pr-preview-$(webapp.slotName)'

- task: AzureCLI@2
  displayName: 'Deploy pr image to new slot'
  inputs:
    azureSubscription: $(azure.servicePrincipal)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az webapp config container set \
      --docker-custom-image-name alphasitecrdev.azurecr.io/$(azureContainerRegistry.repository):$(azureContainerRegistry.tag) \
      --docker-registry-server-url $(azureContainerRegistry.domain) \
      --docker-registry-server-user alphasiteCRdev \
      --docker-registry-server-password $(DOCKER_REGISTRY_SERVER_PASSWORD) \
      --name $(webapp.name) \
      --slot pr-preview-$(webapp.slotName) \
      --resource-group $(webapp.resourceGroup)

- task: GitHubComment@0
  displayName: "Post a comment with a link to the new PR preview"
  inputs:
    gitHubConnection: 'Adam''sGitHub-9/15/2023'
    repositoryName: '$(Build.Repository.Name)'
    comment: 'Check out a preview of your pull request here: https://$(webapp.name)-$(webapp.slotName).azurewebsites.net'