name: Dynamic Application Security Tests

on:  
  push:
    branches: [main]

jobs:
  zap-proxy-scan:
    name: ZAP Proxy Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        env:
          CI: true
          
      - name: Docker Build
        run: docker build --build-arg AEM_GRAPHQL_ENDPOINT=${{secrets.AEM_GRAPHQL_ENDPOINT}} -t sc-labs .
        env:
          CI: true
          AEM_GRAPHQL_ENDPOINT: ${{secrets.AEM_GRAPHQL_ENDPOINT}}

      - name: Docker run
        run: docker run -d -p 3000:3000 sc-labs
        env:
          CI: true
          AEM_GRAPHQL_ENDPOINT: ${{secrets.AEM_GRAPHQL_ENDPOINT}}

      - name: OWASP ZAP FULL Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: "http://localhost:3000"
          fail_action: "false"
          token: ${{ secrets.GITHUB_TOKEN }}